package aplikasi.kulakan.model;
// Generated Nov 11, 2016 9:35:20 PM by Hibernate Tools 4.3.1

import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Barang generated by hbm2java
 */
@Entity
@Table(name="barang")
@XmlRootElement
public class Barang  implements java.io.Serializable {

     @Id
     @GeneratedValue
     @Column(name="id_barang")
     private int idBarang;
     
     @Column(name="kode_barang")
     private String kodeBarang;
     
     @Column(name="nama_barang")
     private String namaBarang;
     
     @Column(name="deskripsi_barang")
     private String deskripsiBarang;
     
     @OneToMany(fetch = FetchType.LAZY, mappedBy = "barang", cascade = CascadeType.ALL)
     private List<Kulakan> daftarKulakan;
     
     @Column(name="satuan_terbesar")
     private String satuanTerbesar;
     
     @Column(name="satuan_terkecil")
     private String satuanTerkecil;
     
     @Column(name="jml_satuan_terkecil")
     private int jmlSatuanTerkecil;
     
     @Column(name="harga")
     private int harga;
     
     @Column(name="last_price")
     private int hargaTerakhir;
     
     @Column(name="tipe")
     private int tipe;
     
     @Column(name="jumlah_pembagian")
     private int jumlahPembagian;

    public Barang() {
    }

    public Barang(int idBarang, String kodeBarang, String namaBarang, String deskripsiBarang, List<Kulakan> daftarKulakan, String satuanTerbesar, String satuanTerkecil, int jmlSatuanTerkecil, int harga, int tipe, int jumlahPembagian, int hargaTerakhir) {
        this.idBarang = idBarang;
        this.kodeBarang = kodeBarang;
        this.namaBarang = namaBarang;
        this.deskripsiBarang = deskripsiBarang;
        this.daftarKulakan = daftarKulakan;
        this.satuanTerbesar = satuanTerbesar;
        this.satuanTerkecil = satuanTerkecil;
        this.jmlSatuanTerkecil = jmlSatuanTerkecil;
        this.harga = harga;
        this.tipe = tipe;
        this.jumlahPembagian = jumlahPembagian;
        this.hargaTerakhir = hargaTerakhir;
    }

    public int getHargaTerakhir() {
        return hargaTerakhir;
    }

    public void setHargaTerakhir(int hargaTerakhir) {
        this.hargaTerakhir = hargaTerakhir;
    }

    public int getJumlahPembagian() {
        return jumlahPembagian;
    }

    public void setJumlahPembagian(int jumlahPembagian) {
        this.jumlahPembagian = jumlahPembagian;
    }

    public int getTipe() {
        return tipe;
    }

    public void setTipe(int tipe) {
        this.tipe = tipe;
    }

    public int getHarga() {
        return harga;
    }

    public void setHarga(int harga) {
        this.harga = harga;
    }

    public String getSatuanTerbesar() {
        return satuanTerbesar;
    }

    public void setSatuanTerbesar(String satuanTerbesar) {
        this.satuanTerbesar = satuanTerbesar;
    }

    public String getSatuanTerkecil() {
        return satuanTerkecil;
    }

    public void setSatuanTerkecil(String satuanTerkecil) {
        this.satuanTerkecil = satuanTerkecil;
    }

    public int getJmlSatuanTerkecil() {
        return jmlSatuanTerkecil;
    }

    public void setJmlSatuanTerkecil(int jmlSatuanTerkecil) {
        this.jmlSatuanTerkecil = jmlSatuanTerkecil;
    }

    public String getKodeBarang() {
        return this.kodeBarang;
    }
    
    public void setKodeBarang(String kodeBarang) {
        this.kodeBarang = kodeBarang;
    }
    public String getNamaBarang() {
        return this.namaBarang;
    }
    
    public void setNamaBarang(String namaBarang) {
        this.namaBarang = namaBarang;
    }
    public String getDeskripsiBarang() {
        return this.deskripsiBarang;
    }
    
    public void setDeskripsiBarang(String deskripsiBarang) {
        this.deskripsiBarang = deskripsiBarang;
    }

    public List<Kulakan> getDaftarKulakan() {
        return daftarKulakan;
    }

    public void setDaftarKulakan(List<Kulakan> daftarKulakan) {
        this.daftarKulakan = daftarKulakan;
    }

    public int getIdBarang() {
        return idBarang;
    }

    public void setIdBarang(int idBarang) {
        this.idBarang = idBarang;
    }
  
    @Override
    public String toString() {
        return kodeBarang + " - " + namaBarang;
    }
}


