package aplikasi.kulakan.model;
// Generated Nov 11, 2016 9:35:20 PM by Hibernate Tools 4.3.1

import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;




/**
 * Supplier generated by hbm2java
 */
@Entity
@Table(name="table_supplier")
@XmlRootElement
public class Supplier  implements java.io.Serializable {

     @Id
     @Column(name="kode_supplier")
     private String kodeSupplier;
     
     @Column(name="nama_supplier")
     private String namaSupplier;
     
     @Column(name="alamat_supplier")
     private String alamatSupplier;
     
     @Column(name="telpon_supplier")
     private String telponSupplier;
     
     @OneToMany(fetch = FetchType.LAZY, mappedBy = "supplier", cascade = CascadeType.ALL)
     private List<Kulakan> daftarKulakan;

    public Supplier() {
    }

    public Supplier(String kodeSupplier, String namaSupplier, String alamatSupplier, String telponSupplier) {
       this.kodeSupplier = kodeSupplier;
       this.namaSupplier = namaSupplier;
       this.alamatSupplier = alamatSupplier;
       this.telponSupplier = telponSupplier;
    }
   
    public String getKodeSupplier() {
        return this.kodeSupplier;
    }
    
    public void setKodeSupplier(String kodeSupplier) {
        this.kodeSupplier = kodeSupplier;
    }
    public String getNamaSupplier() {
        return this.namaSupplier;
    }
    
    public void setNamaSupplier(String namaSupplier) {
        this.namaSupplier = namaSupplier;
    }
    public String getAlamatSupplier() {
        return this.alamatSupplier;
    }
    
    public void setAlamatSupplier(String alamatSupplier) {
        this.alamatSupplier = alamatSupplier;
    }
    public String getTelponSupplier() {
        return this.telponSupplier;
    }
    
    public void setTelponSupplier(String telponSupplier) {
        this.telponSupplier = telponSupplier;
    }

    public List<Kulakan> getDaftarKulakan() {
        return daftarKulakan;
    }

}


