/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi.kulakan.view;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author USER
 */
public class BarangView extends javax.swing.JPanel {

    /**
     * Creates new form BarangView
     */
    public BarangView() {
        initComponents();
        this.showUnit(false);
    }
    private void showUnit(boolean cond){
//        this.labelBiggestUnit.setVisible(cond);
        this.labelSmallestUnit.setVisible(cond);
//        this.satuanTerbesarField.setVisible(cond);
        this.satuanTerkecilField.setVisible(cond);
        this.labelSatuanBesar.setVisible(cond);
        this.labelSatuanKecil.setVisible(cond);
        this.jmlSatuanKecilField.setVisible(cond);
        this.persenPembagian.setEnabled(false);
    }

    public JButton getImportButton() {
        return importButton;
    }

    public void setImportButton(JButton importButton) {
        this.importButton = importButton;
    }

    public JTextField getPersenPembagian() {
        return persenPembagian;
    }

    public void setPersenPembagian(JTextField persenPembagian) {
        this.persenPembagian = persenPembagian;
    }

    public JComboBox<String> getTipeBarang() {
        return tipeBarang;
    }

    public void setTipeBarang(JComboBox<String> tipeBarang) {
        this.tipeBarang = tipeBarang;
    }

    public JButton getExportButton() {
        return exportButton;
    }

    public void setExportButton(JButton exportButton) {
        this.exportButton = exportButton;
    }

    public JTextArea getDeskripsiField() {
        return deskripsiField;
    }

    public void setDeskripsiField(JTextArea deskripsiField) {
        this.deskripsiField = deskripsiField;
    }

    public JTextField getKodeBarangField() {
        return kodeBarangField;
    }

    public void setKodeBarangField(JTextField kodeBarangField) {
        this.kodeBarangField = kodeBarangField;
    }

    public JTextField getKodeParamField() {
        return kodeParamField;
    }

    public void setKodeParamField(JTextField kodeParamField) {
        this.kodeParamField = kodeParamField;
    }

    public JTextField getNamaBarangField() {
        return namaBarangField;
    }

    public void setNamaBarangField(JTextField namaBarangField) {
        this.namaBarangField = namaBarangField;
    }

    public JTextField getNamaParamField() {
        return namaParamField;
    }

    public void setNamaParamField(JTextField namaParamField) {
        this.namaParamField = namaParamField;
    }

    public JButton getSaveButton() {
        return saveButton;
    }

    public void setSaveButton(JButton saveButton) {
        this.saveButton = saveButton;
    }

    public JButton getSearchButton() {
        return searchButton;
    }

    public void setSearchButton(JButton searchButton) {
        this.searchButton = searchButton;
    }

    public JTable getViewTable() {
        return viewTable;
    }

    public void setViewTable(JTable viewTable) {
        this.viewTable = viewTable;
    }

    public JTextField getJmlSatuanKecilField() {
        return jmlSatuanKecilField;
    }

    public void setJmlSatuanKecilField(JTextField jmlSatuanKecilField) {
        this.jmlSatuanKecilField = jmlSatuanKecilField;
    }

    public JLabel getLabelSatuanBesar() {
        return labelSatuanBesar;
    }

    public void setLabelSatuanBesar(JLabel labelSatuanBesar) {
        this.labelSatuanBesar = labelSatuanBesar;
    }

    public JLabel getLabelSatuanKecil() {
        return labelSatuanKecil;
    }

    public void setLabelSatuanKecil(JLabel labelSatuanKecil) {
        this.labelSatuanKecil = labelSatuanKecil;
    }

    public JTextField getSatuanTerbesarField() {
        return satuanTerbesarField;
    }

    public void setSatuanTerbesarField(JTextField satuanTerbesarField) {
        this.satuanTerbesarField = satuanTerbesarField;
    }

    public JTextField getSatuanTerkecilField() {
        return satuanTerkecilField;
    }

    public void setSatuanTerkecilField(JTextField satuanTerkecilField) {
        this.satuanTerkecilField = satuanTerkecilField;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kodeBarangField = new javax.swing.JTextField();
        namaBarangField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        deskripsiField = new javax.swing.JTextArea();
        saveButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        labelBiggestUnit = new javax.swing.JLabel();
        satuanTerbesarField = new javax.swing.JTextField();
        labelSmallestUnit = new javax.swing.JLabel();
        satuanTerkecilField = new javax.swing.JTextField();
        labelSatuanBesar = new javax.swing.JLabel();
        jmlSatuanKecilField = new javax.swing.JTextField();
        labelSatuanKecil = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tipeBarang = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        persenPembagian = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        exportButton = new javax.swing.JButton();
        importButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        viewTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        kodeParamField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        namaParamField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tambah Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 288));

        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        jLabel1.setText("Kode Barang");

        jLabel3.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        jLabel3.setText("Deskripsi Barang");

        kodeBarangField.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N

        namaBarangField.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N

        deskripsiField.setColumns(20);
        deskripsiField.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        deskripsiField.setRows(5);
        jScrollPane1.setViewportView(deskripsiField);

        saveButton.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        saveButton.setText("SIMPAN");

        jLabel5.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        jLabel5.setText("Nama Barang");

        labelBiggestUnit.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        labelBiggestUnit.setText("Satuan");

        satuanTerbesarField.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N

        labelSmallestUnit.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        labelSmallestUnit.setText("Satuan Terkecil");

        satuanTerkecilField.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        satuanTerkecilField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                satuanTerkecilFieldFocusLost(evt);
            }
        });

        labelSatuanBesar.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        labelSatuanBesar.setText("1 Satuan Besar Terdiri Dari");

        jmlSatuanKecilField.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N

        labelSatuanKecil.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        labelSatuanKecil.setText("Satuan Kecil");

        jLabel6.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        jLabel6.setText("Tipe ");

        tipeBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Tipe --", "Sendiri", "Titipan" }));

        jLabel7.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        jLabel7.setText("Persen Pembagian");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(kodeBarangField, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel5))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(namaBarangField, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel6))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(tipeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel7))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(persenPembagian, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(labelBiggestUnit))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(satuanTerbesarField, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(labelSmallestUnit))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(satuanTerkecilField, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(labelSatuanBesar)
                .addGap(6, 6, 6)
                .addComponent(jmlSatuanKecilField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(labelSatuanKecil))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(saveButton))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(kodeBarangField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel5)
                .addGap(12, 12, 12)
                .addComponent(namaBarangField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel6)
                .addGap(6, 6, 6)
                .addComponent(tipeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel7)
                .addGap(6, 6, 6)
                .addComponent(persenPembagian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(labelBiggestUnit)
                .addGap(6, 6, 6)
                .addComponent(satuanTerbesarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(labelSmallestUnit)
                .addGap(4, 4, 4)
                .addComponent(satuanTerkecilField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jmlSatuanKecilField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSatuanBesar)
                            .addComponent(labelSatuanKecil))))
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveButton))
        );

        jPanel3.setPreferredSize(new java.awt.Dimension(500, 449));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        exportButton.setBackground(new java.awt.Color(255, 255, 255));
        exportButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exportButton.setForeground(new java.awt.Color(0, 0, 0));
        exportButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/kulakan/images/1480358423_export.png"))); // NOI18N
        exportButton.setText("Export To Excel");
        exportButton.setToolTipText("Export To Excel");
        exportButton.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        exportButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exportButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        importButton.setBackground(new java.awt.Color(255, 255, 255));
        importButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        importButton.setForeground(new java.awt.Color(0, 0, 0));
        importButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/kulakan/images/import-icon.png"))); // NOI18N
        importButton.setText("Import Data");
        importButton.setToolTipText("Export To Excel");
        importButton.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        importButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        importButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exportButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(importButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(importButton)
                    .addComponent(exportButton))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        viewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(viewTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 557;
        gridBagConstraints.ipady = 396;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 8, 2);
        jPanel5.add(jScrollPane2, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        jLabel4.setText("Kode Barang");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 12, 0, 0);
        jPanel5.add(jLabel4, gridBagConstraints);

        kodeParamField.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 115;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 0, 0);
        jPanel5.add(kodeParamField, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        jLabel2.setText("Nama Barang");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 12, 0, 0);
        jPanel5.add(jLabel2, gridBagConstraints);

        namaParamField.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 123;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
        jPanel5.add(namaParamField, gridBagConstraints);

        searchButton.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/kulakan/images/1478801823_11_Search.png"))); // NOI18N
        searchButton.setText("CARI");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 12, 0, 0);
        jPanel5.add(searchButton, gridBagConstraints);

        jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void satuanTerkecilFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_satuanTerkecilFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_satuanTerkecilFieldFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea deskripsiField;
    private javax.swing.JButton exportButton;
    private javax.swing.JButton importButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jmlSatuanKecilField;
    private javax.swing.JTextField kodeBarangField;
    private javax.swing.JTextField kodeParamField;
    private javax.swing.JLabel labelBiggestUnit;
    private javax.swing.JLabel labelSatuanBesar;
    private javax.swing.JLabel labelSatuanKecil;
    private javax.swing.JLabel labelSmallestUnit;
    private javax.swing.JTextField namaBarangField;
    private javax.swing.JTextField namaParamField;
    private javax.swing.JTextField persenPembagian;
    private javax.swing.JTextField satuanTerbesarField;
    private javax.swing.JTextField satuanTerkecilField;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox<String> tipeBarang;
    private javax.swing.JTable viewTable;
    // End of variables declaration//GEN-END:variables
}
