/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi.kulakan.view;

import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author guest
 */
public class JournalPage extends javax.swing.JPanel {

    /**
     * Creates new form PengeluaranPage
     */
    public JournalPage() {
        initComponents();
        jLabel2.setFont(new Font(Font.SANS_SERIF, Font.BOLD, 14));
        jLabel6.setFont(new Font(Font.SANS_SERIF, Font.BOLD, 14));
        jLabel7.setFont(new Font(Font.SANS_SERIF, Font.BOLD, 14));
        jLabel8.setFont(new Font(Font.SANS_SERIF, Font.BOLD, 14));
        jLabel9.setFont(new Font(Font.SANS_SERIF, Font.BOLD, 14));
        jLabel10.setFont(new Font(Font.SANS_SERIF, Font.BOLD, 14));
    }

    public JTextField getTanggalField() {
        return tanggalField;
    }

    public void setTanggalField(JTextField tanggalField) {
        this.tanggalField = tanggalField;
    }
    
    public JTable getViewTable() {
        return viewTable;
    }

    public void setViewTable(JTable viewTable) {
        this.viewTable = viewTable;
    }

    public JComboBox<String> getMonthOption() {
        return monthOption;
    }

    public void setMonthOption(JComboBox<String> monthOption) {
        this.monthOption = monthOption;
    }

    public JButton getPrintButton() {
        return printButton;
    }

    public void setPrintButton(JButton printButton) {
        this.printButton = printButton;
    }

    public JButton getSearchButton() {
        return searchButton;
    }

    public void setSearchButton(JButton searchButton) {
        this.searchButton = searchButton;
    }

    public JComboBox<String> getTahunParameter() {
        return tahunParameter;
    }

    public void setTahunParameter(JComboBox<String> tahunParameter) {
        this.tahunParameter = tahunParameter;
    }

    public JLabel getTotalKulakanLabel() {
        return totalKulakanLabel;
    }

    public void setTotalKulakanLabel(JLabel totalKulakanLabel) {
        this.totalKulakanLabel = totalKulakanLabel;
    }

    public JLabel getTotalLabaLabel() {
        return totalLabaLabel;
    }

    public void setTotalLabaLabel(JLabel totalLabaLabel) {
        this.totalLabaLabel = totalLabaLabel;
    }

    public JLabel getTotalMarginLabel() {
        return totalMarginLabel;
    }

    public void setTotalMarginLabel(JLabel totalMarginLabel) {
        this.totalMarginLabel = totalMarginLabel;
    }

    public JLabel getTotalPemasukanLabel() {
        return totalPemasukanLabel;
    }

    public void setTotalPemasukanLabel(JLabel totalPemasukanLabel) {
        this.totalPemasukanLabel = totalPemasukanLabel;
    }

    public JLabel getTotalPengeluaranAllLabel() {
        return totalPengeluaranAllLabel;
    }

    public void setTotalPengeluaranAllLabel(JLabel totalPengeluaranAllLabel) {
        this.totalPengeluaranAllLabel = totalPengeluaranAllLabel;
    }

    public JLabel getTotalPengeluaranLabel() {
        return totalPengeluaranLabel;
    }

    public void setTotalPengeluaranLabel(JLabel totalPengeluaranLabel) {
        this.totalPengeluaranLabel = totalPengeluaranLabel;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        monthOption = new javax.swing.JComboBox<>();
        searchButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        printButton = new javax.swing.JButton();
        tahunParameter = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tanggalField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        totalPengeluaranAllLabel = new javax.swing.JLabel();
        totalMarginLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        totalPemasukanLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        totalPengeluaranLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        totalKulakanLabel = new javax.swing.JLabel();
        totalLabaLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 75));

        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        jLabel1.setText("Bulan");

        monthOption.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        monthOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        searchButton.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/kulakan/images/1478801823_11_Search.png"))); // NOI18N
        searchButton.setText("CARI");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        printButton.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        printButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/kulakan/images/1480022303_BT_printer.png"))); // NOI18N
        printButton.setText("Export To Excel");
        printButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        printButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        tahunParameter.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        tahunParameter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        jLabel3.setText("Tahun");

        jLabel4.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        jLabel4.setText("Tanggal");

        tanggalField.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(monthOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tahunParameter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addComponent(tanggalField, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printButton)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(monthOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(tahunParameter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(tanggalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printButton))
                .addGap(8, 8, 8))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setPreferredSize(new java.awt.Dimension(926, 500));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(350, 300));

        viewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        viewTable.setMinimumSize(new java.awt.Dimension(300, 64));
        jScrollPane1.setViewportView(viewTable);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.NORTH);

        jPanel3.setInheritsPopupMenu(true);
        jPanel3.setPreferredSize(new java.awt.Dimension(450, 200));

        jLabel8.setText("Total Kulakan :");

        totalPengeluaranAllLabel.setBackground(new java.awt.Color(255, 51, 0));
        totalPengeluaranAllLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        totalPengeluaranAllLabel.setForeground(java.awt.Color.white);
        totalPengeluaranAllLabel.setText("Rp...");
        totalPengeluaranAllLabel.setOpaque(true);

        totalMarginLabel.setBackground(new java.awt.Color(51, 204, 0));
        totalMarginLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        totalMarginLabel.setForeground(java.awt.Color.white);
        totalMarginLabel.setText("Rp...");
        totalMarginLabel.setOpaque(true);

        jLabel6.setText("Total Pengeluaran :");

        totalPemasukanLabel.setBackground(new java.awt.Color(51, 204, 0));
        totalPemasukanLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        totalPemasukanLabel.setForeground(java.awt.Color.white);
        totalPemasukanLabel.setText("Rp...");
        totalPemasukanLabel.setOpaque(true);

        jLabel9.setText("Total Pengeluaran :");

        totalPengeluaranLabel.setBackground(new java.awt.Color(255, 153, 0));
        totalPengeluaranLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        totalPengeluaranLabel.setForeground(java.awt.Color.white);
        totalPengeluaranLabel.setText("Rp...");
        totalPengeluaranLabel.setOpaque(true);

        jLabel7.setText("Total Pemasukan :");

        totalKulakanLabel.setBackground(new java.awt.Color(255, 153, 0));
        totalKulakanLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        totalKulakanLabel.setForeground(java.awt.Color.white);
        totalKulakanLabel.setText("Rp...");
        totalKulakanLabel.setOpaque(true);

        totalLabaLabel.setBackground(new java.awt.Color(51, 204, 0));
        totalLabaLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        totalLabaLabel.setForeground(java.awt.Color.white);
        totalLabaLabel.setText("Rp...");
        totalLabaLabel.setOpaque(true);

        jLabel10.setText("Total Laba :");

        jLabel2.setText("Total Margin :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalLabaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(totalPengeluaranLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(totalMarginLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(totalPemasukanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(totalKulakanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalPengeluaranAllLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(totalPemasukanLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalKulakanLabel)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalPengeluaranLabel)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(totalMarginLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(totalPengeluaranAllLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(totalLabaLabel))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.LINE_END);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> monthOption;
    private javax.swing.JButton printButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox<String> tahunParameter;
    private javax.swing.JTextField tanggalField;
    private javax.swing.JLabel totalKulakanLabel;
    private javax.swing.JLabel totalLabaLabel;
    private javax.swing.JLabel totalMarginLabel;
    private javax.swing.JLabel totalPemasukanLabel;
    private javax.swing.JLabel totalPengeluaranAllLabel;
    private javax.swing.JLabel totalPengeluaranLabel;
    private javax.swing.JTable viewTable;
    // End of variables declaration//GEN-END:variables
}
