/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi.kulakan.view;

import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/**
 *
 * @author USER
 */
public class KulakanPageContainer extends javax.swing.JPanel {

    /**
     * Creates new form KulakanPage_new
     */
    public KulakanPageContainer() {
        initComponents();
    }

    public JTabbedPane getWorkspace() {
        return workspace;
    }

    public void setWorkspace(JTabbedPane workspace) {
        this.workspace = workspace;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        workspace = new javax.swing.JTabbedPane();

        setLayout(new java.awt.BorderLayout());

        workspace.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        add(workspace, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane workspace;
    // End of variables declaration//GEN-END:variables
}
