/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi.kulakan.view;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author USER
 */
public class KulakanPage extends javax.swing.JPanel {

    /**
     * Creates new form KulakanPage
     */
    public KulakanPage() {
        initComponents();
    }

    public JTextField getTanggalField() {
        return tanggalField;
    }

    public void setTanggalField(JTextField tanggalField) {
        this.tanggalField = tanggalField;
    }

    public JButton getPrintButton() {
        return printButton;
    }

    public void setPrintButton(JButton printButton) {
        this.printButton = printButton;
    }

    public JButton getAddToCartButton() {
        return AddToCartButton;
    }

    public void setAddToCartButton(JButton AddToCartButton) {
        this.AddToCartButton = AddToCartButton;
    }

    public JComboBox<String> getMonthOption() {
        return monthOption;
    }

    public void setMonthOption(JComboBox<String> monthOption) {
        this.monthOption = monthOption;
    }

    public JButton getSearchButton() {
        return searchButton;
    }

    public void setSearchButton(JButton searchButton) {
        this.searchButton = searchButton;
    }

    public JComboBox<String> getSupplierNameOption() {
        return supplierNameOption;
    }

    public void setSupplierNameOption(JComboBox<String> supplierNameOption) {
        this.supplierNameOption = supplierNameOption;
    }

    public JTable getViewTable() {
        return viewTable;
    }

    public void setViewTable(JTable viewTable) {
        this.viewTable = viewTable;
    }

    public JComboBox<String> getTahunParameter() {
        return tahunParameter;
    }

    public void setTahunParameter(JComboBox<String> tahunParameter) {
        this.tahunParameter = tahunParameter;
    }

    public JTextField getBarangField() {
        return barangField;
    }

    public void setBarangField(JTextField barangField) {
        this.barangField = barangField;
    }

    public JButton getRekapButton() {
        return rekapButton;
    }

    public void setRekapButton(JButton rekapButton) {
        this.rekapButton = rekapButton;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        monthOption = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        barangField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        supplierNameOption = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        tahunParameter = new javax.swing.JComboBox<>();
        tanggalField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        printButton = new javax.swing.JButton();
        rekapButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        AddToCartButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 110));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 110));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(600, 106));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Tgl");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 13, 52, -1));
        jLabel5.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        jLabel4.setText("Nama Barang");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 44, -1, -1));

        monthOption.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        monthOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(monthOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 39, 177, -1));

        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        jLabel1.setText("Bulan");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 44, 52, -1));

        searchButton.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/kulakan/images/1478801823_11_Search.png"))); // NOI18N
        searchButton.setText("CARI");
        jPanel3.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 70, 257, 30));

        barangField.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        jPanel3.add(barangField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 156, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        jLabel3.setText("Tahun");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 78, 52, -1));

        supplierNameOption.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        supplierNameOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        supplierNameOption.setMaximumSize(new java.awt.Dimension(120, 25));
        jPanel3.add(supplierNameOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 8, 156, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        jLabel2.setText("Supplier");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 13, 95, -1));

        tahunParameter.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        tahunParameter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(tahunParameter, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 73, 177, -1));
        jPanel3.add(tanggalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 9, 177, -1));

        jPanel1.add(jPanel3, java.awt.BorderLayout.WEST);

        jPanel4.setPreferredSize(new java.awt.Dimension(600, 88));

        printButton.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        printButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/kulakan/images/1480022303_BT_printer.png"))); // NOI18N
        printButton.setText("EXPORT");
        printButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        printButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        rekapButton.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12));
        rekapButton.setText("REKAP");
        rekapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rekapButtonActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(10, 30));

        AddToCartButton.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        AddToCartButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/kulakan/images/iconfinder_notification_add_48783.png"))); // NOI18N
        AddToCartButton.setText("TAMBAH");
        AddToCartButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AddToCartButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddToCartButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rekapButton)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AddToCartButton)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(printButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rekapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, java.awt.BorderLayout.EAST);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setMinimumSize(new java.awt.Dimension(1200, 390));
        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 390));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        viewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(viewTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 777;
        gridBagConstraints.ipady = 400;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jScrollPane1, gridBagConstraints);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void rekapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rekapButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rekapButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddToCartButton;
    private javax.swing.JTextField barangField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> monthOption;
    private javax.swing.JButton printButton;
    private javax.swing.JButton rekapButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox<String> supplierNameOption;
    private javax.swing.JComboBox<String> tahunParameter;
    private javax.swing.JTextField tanggalField;
    private javax.swing.JTable viewTable;
    // End of variables declaration//GEN-END:variables
}
