/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi.kulakan.view;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author USER
 */
public class PrintOptionGeneral extends javax.swing.JPanel {

    /**
     * Creates new form PrintOptionKulakan
     */
    public PrintOptionGeneral() {
        initComponents();
    }

    public JComboBox<String> getBulanOption() {
        return bulanOption;
    }

    public void setBulanOption(JComboBox<String> bulanOption) {
        this.bulanOption = bulanOption;
    }

    public JComboBox<String> getTahunOption() {
        return tahunOption;
    }

    public void setTahunOption(JComboBox<String> tahunOption) {
        this.tahunOption = tahunOption;
    }

    public JButton getPrintButton() {
        return printButton;
    }

    public void setPrintButton(JButton printButton) {
        this.printButton = printButton;
    }

    public JTextField getTanggalField() {
        return tanggalField;
    }

    public void setTanggalField(JTextField tanggalField) {
        this.tanggalField = tanggalField;
    }

    public JLabel getTanggalLabel() {
        return tanggalLabel;
    }

    public void setTanggalLabel(JLabel tanggalLabel) {
        this.tanggalLabel = tanggalLabel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bulanOption = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        tahunOption = new javax.swing.JComboBox<>();
        printButton = new javax.swing.JButton();
        tanggalLabel = new javax.swing.JLabel();
        tanggalField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12));
        jLabel1.setText("Bulan");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 11, -1, -1));

        bulanOption.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bulanOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(bulanOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 6, 239, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12));
        jLabel2.setText("Tahun");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 40, -1, -1));

        tahunOption.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tahunOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        tahunOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahunOptionActionPerformed(evt);
            }
        });
        add(tahunOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 37, 239, -1));

        printButton.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12));
        printButton.setText("CETAK");
        add(printButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 103, -1, -1));

        tanggalLabel.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12));
        tanggalLabel.setText("Tanggal");
        add(tanggalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 71, -1, -1));
        add(tanggalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 67, 105, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void tahunOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahunOptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tahunOptionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bulanOption;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton printButton;
    private javax.swing.JComboBox<String> tahunOption;
    private javax.swing.JTextField tanggalField;
    private javax.swing.JLabel tanggalLabel;
    // End of variables declaration//GEN-END:variables
}
